name: AI 自動筆

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version you need

      # Add this step to configure Git identity
      - name: Configure Git Identity
        run: |
          git config --global user.name "Craftguy-Billies"
          git config --global user.email "kwantszlong1555@gmail.com"

      # Runs your Python script
      - name: Run test
        run: python plan_a.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
            commit_message: Changed files
            branch: ${{ github.ref }}
            force: true
